---
# We just wrap `build` so this is really it
name: "jellyfin-ffmpeg"
version: "7.0.2-3"
packages:
  - bullseye-amd64
  - bullseye-armhf
  - bullseye-arm64
  - bookworm-amd64
  - bookworm-armhf
  - bookworm-arm64
  - focal-amd64
  - focal-armhf
  - focal-arm64
  - jammy-amd64
  - jammy-armhf
  - jammy-arm64
  - noble-amd64
  - noble-armhf
  - noble-arm64
